on: pull_request

name: Doc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: actions-rs/cargo@v1
        with: 
          command: doc