name: Chaos Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - x86_64-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - i686-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
        version:
          - stable
          - nightly
        include:
        - toolchain: x86_64-pc-windows-msvc
          os: windows-latest
        - toolchain: x86_64-pc-windows-gnu
          os: windows-latest
        - toolchain: i686-pc-windows-msvc
          os: windows-latest
        - toolchain: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - toolchain: x86_64-apple-darwin
          os: macOS-latest

    name: ${{ matrix.version }} - ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-${{ matrix.toolchain }}
          default: true

      - name: Chaos Tests (Core)
        run: cargo test --verbose
        working-directory: ./artillery-core
